### ISSUE TITLE
Consistent proto field numbers

### ISSUE THREAD

**Issue by anatheka** [oxisto/owl2protobuf#3]
We have somehow to ensure, that the field number does not change at each proto file creation. 
Furthermore, we have to deal with properties that are added in future.

**Comment by anatheka** [comment]
We could use non-cryptographic hash functions. We must somehow ensure, that the target number is in a defined range. Either the hash function can do this or we do it via modulo.

**Comment by anatheka** [comment]
> You should use the field numbers 1 through 15 for the most-frequently-set fields. Lower field number values take less space in the wire format. For example, field numbers in the range 1 through 15 take one byte to encode. Field numbers in the range 16 through 2047 take two bytes. You can find out more about this in [Protocol Buffer Encoding](https://protobuf.dev/programming-guides/encoding#structure)

(Source: https://protobuf.dev/programming-guides/proto3/#assigning)

**Comment by oxisto** [comment]
Initial try done by #24
